# Base URL
@rootUrl = http://localhost:3000

### root endpoint
GET {{rootUrl}}/

### get all books
GET {{rootUrl}}/api/books

### Get book by ID
GET {{rootUrl}}/api/books/3

### Create a new book
POST {{rootUrl}}/api/books
Content-Type: application/json

{
    "title": "malcom",
    "author":"gladwell",
    "genre": "fantasy",
    "yop": "4090"
}

### Update book
PUT http://localhost:3000/api/books/6
Content-Type: application/json

{
  "author": "Malcolm Gladwell",
  "title": "Outliers",
  "yop": "2008",
  "genre": "Psychology"
}


### Delete book
DELETE {{rootUrl}}/api/books/4