# Base URL
@rootUrl = http://localhost:3000

### root endpoint
GET {{rootUrl}}/

### get all books
GET {{rootUrl}}/api/books

### Get book by ID
GET {{rootUrl}}/api/books/1

### Create a new book
POST {{rootUrl}}/api/books


### Update todo
PUT {{rootUrl}}/api/books/1
Content-Type: application/json

### Delete todo
DELETE {{rootUrl}}/api/books/1